name: iec
description: "A Flutter project to test in IEC."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^7.1.0
  flutter_bloc: ^7.1.0
  screenshot: ^2.5.0
  path_provider: ^2.1.3
  image_gallery_saver: ^2.0.3
  flutter_svg: ^2.0.10+1
  flutter_colorpicker: ^1.1.0
  flutter_hooks: ^0.20.5
  path_drawing: ^1.0.1
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  flutter_portal: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

